import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Deux barres latérales, une par nature de contenu.
 *
 * `autogenerated` évite d'avoir à lister chaque fichier : un ADR ajouté dans
 * `docs/adr/` apparaît sans toucher à ce fichier, et l'API régénérée par TypeDoc
 * suit ses propres dossiers.
 */
const sidebars: SidebarsConfig = {
  adrSidebar: [{ type: 'autogenerated', dirName: 'adr' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
};

export default sidebars;
