/**
 * @file ISessionShareService.ts
 * @description Port abstrait pour le partage collaboratif de session (F5).
 *              Abstract port for collaborative session sharing (F5).
 *
 *              Distinct de {@link IRealtimeService} (positions live F4) : ce port
 *              gère le ROSTER partagé (meta + membres / points de départ) d'une
 *              session, publié sur Firebase RTDB pour permettre à des invités de
 *              rejoindre via un deep link `mivro://session/{id}`.
 *              Distinct from {@link IRealtimeService} (F4 live positions): this
 *              port manages the shared ROSTER (meta + members / start points) of
 *              a session, published to Firebase RTDB so guests can join via a
 *              `mivro://session/{id}` deep link.
 *
 *              Permet de swapper le backend de partage sans toucher au métier ni
 *              à la présentation.
 *              Allows swapping the sharing backend without touching business
 *              logic nor presentation.
 *
 *              ⚠️ RGPD : la session expire (24h guest / 7j compte) ; elle est
 *              supprimée en fin de session ; les coordonnées exactes ne sont
 *              jamais loggées.
 *
 *              Implémentations : FirebaseSessionShareService (infrastructure/).
 *
 * @module core/ports/ISessionShareService
 */

// [ADDED] F5 — Port ISessionShareService + erreur typée
import type { Coordinates } from '@entities/Location';
import type {
  SharedSession,
  SharedSessionMember,
  SharedSessionOwnerType,
} from '@entities/SharedSession';

/**
 * Fonction de désabonnement retournée par {@link ISessionShareService.subscribeToSharedSession}.
 * Unsubscribe function returned by {@link ISessionShareService.subscribeToSharedSession}.
 */
export type SessionShareUnsubscribe = () => void;

/**
 * Callback invoqué à chaque changement de la session partagée (meta + membres).
 * Callback invoked on every change of the shared session (meta + members).
 *
 * Reçoit la session **validée** (Zod), ou `null` si elle n'existe plus.
 * Receives the **validated** (Zod) session, or `null` if it no longer exists.
 *
 * @param session - Session partagée validée ou null / Validated shared session or null
 */
export type SharedSessionUpdateHandler = (session: SharedSession | null) => void;

/**
 * Résultat de la création d'une session partagée.
 * Result of creating a shared session.
 */
export interface CreateSharedSessionResult {
  /** Identifiant de la session partagée / Shared session identifier */
  readonly sessionId: string;
  /** Lien profond `mivro://session/{id}` / Deep link */
  readonly link: string;
  /** Date d'expiration (epoch ms) / Expiration date (epoch ms) */
  readonly expiresAt: number;
}

/**
 * Membre à ajouter au roster (sans `memberId`, généré par l'appelant/adapter).
 * Member to add to the roster (without `memberId`, generated by caller/adapter).
 */
export type SharedSessionMemberInput = SharedSessionMember;

/**
 * Port abstrait pour le service de partage de session.
 * Abstract port for the session sharing service.
 *
 * @example
 *   const { sessionId, link } = await shareService.createSharedSession(session, 'guest');
 *   const unsub = shareService.subscribeToSharedSession(sessionId, (shared) => render(shared));
 *   await shareService.joinSharedSession(sessionId, member);
 *   await shareService.updateMidpoint(sessionId, midpoint, radius);
 *   await shareService.deleteSharedSession(sessionId);
 *   unsub();
 */
export interface ISessionShareService {
  /**
   * Publie la session courante sur le backend partagé (meta + membres).
   * Publishes the current session to the shared backend (meta + members).
   *
   * @param session - Session partagée à publier (meta + roster initial) / Shared session to publish
   * @param ownerType - Type de propriétaire (pilote l'expiration) / Owner type (drives expiration)
   * @returns Identifiant, lien profond et date d'expiration / Identifier, deep link and expiration
   * @throws {SessionShareError} Si la publication échoue / If the publish fails
   */
  createSharedSession(
    session: SharedSession,
    ownerType: SharedSessionOwnerType,
  ): Promise<CreateSharedSessionResult>;

  /**
   * Ajoute un membre (point de départ collaboratif) à une session partagée.
   * Adds a member (collaborative start point) to a shared session.
   *
   * @param sessionId - Identifiant de la session / Session identifier
   * @param member - Membre à ajouter / Member to add
   * @throws {SessionShareError} Codes `not_found`, `expired`, `closed`, `network`… / Typed error codes
   */
  joinSharedSession(sessionId: string, member: SharedSessionMemberInput): Promise<void>;

  /**
   * Récupère une fois l'état courant d'une session partagée (lecture ponctuelle).
   * Fetches the current state of a shared session once (one-shot read).
   *
   * @param sessionId - Identifiant de la session / Session identifier
   * @returns Session partagée validée, ou null si absente / Validated shared session, or null
   * @throws {SessionShareError} Si la lecture échoue / If the read fails
   */
  fetchSharedSession(sessionId: string): Promise<SharedSession | null>;

  /**
   * S'abonne aux changements d'une session partagée (meta + membres live).
   * Subscribes to a shared session's changes (meta + members live).
   *
   * Le handler est appelé immédiatement avec l'état courant puis à chaque
   * changement. Les données sont validées via Zod (TS-004).
   * The handler is called immediately with the current state then on each
   * change. Data is validated via Zod (TS-004).
   *
   * @param sessionId - Identifiant de la session / Session identifier
   * @param onUpdate - Handler appelé à chaque changement / Handler called on each change
   * @returns Fonction de désabonnement / Unsubscribe function
   * @throws {SessionShareError} Si l'abonnement ne peut être établi / If the subscription cannot be established
   */
  subscribeToSharedSession(
    sessionId: string,
    onUpdate: SharedSessionUpdateHandler,
  ): SessionShareUnsubscribe;

  /**
   * Met à jour le midpoint recalculé dans la meta de la session.
   * Updates the recomputed midpoint in the session meta.
   *
   * @param sessionId - Identifiant de la session / Session identifier
   * @param midpoint - Coordonnées du midpoint / Midpoint coordinates
   * @param radius - Rayon de zone en mètres / Zone radius in meters
   * @throws {SessionShareError} Si la mise à jour échoue / If the update fails
   */
  updateMidpoint(sessionId: string, midpoint: Coordinates, radius: number): Promise<void>;

  /**
   * Supprime la session partagée (RGPD — fin de session).
   * Deletes the shared session (GDPR — end of session).
   *
   * Idempotent : ne lève pas si la session n'existe plus.
   * Idempotent: does not throw if the session no longer exists.
   *
   * @param sessionId - Identifiant de la session / Session identifier
   * @throws {SessionShareError} Si la suppression échoue durablement / If removal fails persistently
   */
  deleteSharedSession(sessionId: string): Promise<void>;
}

/**
 * Codes d'erreur typés pour le service de partage de session.
 * Typed error codes for the session sharing service.
 *
 * - `not_configured` : Firebase non configuré (fichiers natifs manquants) / Firebase not configured
 * - `not_found` : Session introuvable (lien invalide/supprimé) / Session not found
 * - `expired` : Session expirée (TTL dépassé) / Session expired (TTL exceeded)
 * - `closed` : Session fermée par le propriétaire / Session closed by owner
 * - `full` : Session pleine (5 membres atteints) / Session full (5 members reached)
 * - `network` : Erreur réseau / connexion / Network or connection error
 * - `permission_denied` : Règles de sécurité refusent l'accès / Security rules deny access
 * - `invalid_data` : Données lues invalides (échec Zod) / Read data invalid (Zod failure)
 * - `unknown` : Erreur inattendue / Unexpected error
 */
export type SessionShareErrorCode =
  | 'not_configured'
  | 'not_found'
  | 'expired'
  | 'closed'
  | 'full'
  | 'network'
  | 'permission_denied'
  | 'invalid_data'
  | 'unknown';

/**
 * Erreur métier typée pour le service de partage de session.
 * Typed business error for the session sharing service.
 *
 * @param message - Message lisible (non affiché tel quel) / Human-readable message
 * @param code - Code d'erreur typé (mappé vers un message i18n) / Typed error code
 * @param cause - Erreur originale optionnelle / Optional original error
 */
export class SessionShareError extends Error {
  constructor(
    message: string,
    public readonly code: SessionShareErrorCode,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'SessionShareError';
  }
}
