#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# harness-lock.sh — the harness Cedric approved, as a list of hashes.
#
#   bash scripts/harness-lock.sh            verify (a sensor: exit 1 on drift)
#   bash scripts/harness-lock.sh --print    print the lock the tree would produce
#   npm run harness:relock                  refresh it (Cedric, in a terminal)
#
# Covers every harness file present (harness_paths.lockable_files): everything
# outside the product zones — dotfiles, tool configs, package.json and the
# lockfiles — plus the files listed in scripts/harness-protected.txt (JOURNAL
# J-045). Any change to
# them — by Edit, by Bash, by a script the guards did not see — turns this
# sensor red until the lock is refreshed. Refreshing requires an interactive
# terminal and refuses to run inside Claude Code, so the agent cannot approve
# its own harness change (JOURNAL J-029). In CI, a PR that touches the lock also
# needs the `harness-change` label, which only Cedric sets.
# ---------------------------------------------------------------------------
set -uo pipefail

# Never read or write Python bytecode: a .pyc planted in the cache would
# replace the source of a guard or of the stdlib (JOURNAL J-052).
export PYTHONDONTWRITEBYTECODE=1 PYTHONPYCACHEPREFIX=/dev/null/mivro-nopyc

cd "$(git rev-parse --show-toplevel)" || exit 1

LOCK="scripts/harness.lock"

compute() {
  printf '# Harness lock — generated by scripts/harness-lock.sh. Do not edit by hand.\n'
  printf '# Refresh: npm run harness:relock (interactive, human only).\n'
  python3 scripts/hooks/harness_paths.py --lockable | while IFS= read -r file; do
    printf '%s  %s\n' "$(shasum -a 256 "$file" | cut -d' ' -f1)" "$file"
  done
}

case "${1:-}" in
  --print)
    compute
    exit 0
    ;;
  --update)
    if [ "${CLAUDECODE:-}" = "1" ] || [ ! -t 0 ] || [ ! -t 1 ]; then
      echo "✖ harness:relock must be run by Cedric in an interactive terminal, outside Claude Code." >&2
      exit 1
    fi
    CURRENT="$(compute)"
    if [ -f "$LOCK" ]; then
      diff <(grep -v '^#' "$LOCK") <(printf '%s\n' "$CURRENT" | grep -v '^#') | sed -n 's/^[<>] /  /p' | sort -u -k2 || true
    fi
    printf 'Approve these harness changes? Type RELOCK to confirm: '
    read -r answer
    if [ "$answer" != "RELOCK" ]; then
      echo "Aborted, lock unchanged."
      exit 1
    fi
    printf '%s\n' "$CURRENT" >"$LOCK"
    echo "✔ $LOCK refreshed. Commit it with the harness change it approves."
    exit 0
    ;;
  "") ;;
  *)
    echo "usage: harness-lock.sh [--print|--update]" >&2
    exit 2
    ;;
esac

if [ ! -f "$LOCK" ]; then
  echo "✖ $LOCK is missing: the harness has no approved state to compare against." >&2
  exit 1
fi

EXPECTED="$(grep -v '^#' "$LOCK")"
ACTUAL="$(compute | grep -v '^#')"
if [ "$EXPECTED" = "$ACTUAL" ]; then
  exit 0
fi

echo "✖ The harness differs from the approved lock ($LOCK):"
# No process substitution here: the Bash sandbox of Claude Code denies /dev/fd
# (JOURNAL J-051), and this sensor runs in the agent's shell.
{
  printf '%s\n' "$EXPECTED" | sed 's/^/< /'
  printf '%s\n' "$ACTUAL" | sed 's/^/> /'
} | awk '
  /^< / { old[$3] = $2 }
  /^> / { new[$3] = $2 }
  END {
    for (f in old) if (!(f in new)) print "  removed   " f
    for (f in new) if (!(f in old)) print "  added     " f
    for (f in new) if ((f in old) && old[f] != new[f]) print "  modified  " f
  }' | sort -k2
cat <<'MSG'

A harness file changed (hooks, sensors, lint/test/arch config, CI, package.json
scripts). If the agent made this change, revert it and explain the need to
Cedric instead. If Cedric approves it, he runs `npm run harness:relock` in his
terminal and commits the lock with the change.
MSG
exit 1
